# Generated by Django 4.2.23 on 2025-12-17 17:43

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CpuNodeInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(help_text='CPU node type name (e.g., CPU_384M, CPU_1500T). Multiple instances of the same type are allowed.', max_length=64)),
                ('is_rentable', models.BooleanField(default=False, help_text='Whether this node type can be rented for booking management')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('PLACEHOLDER', 'Placeholder')], default='AVAILABLE', help_text='Current status of the node instance', max_length=32)),
                ('associated_resource_address', models.CharField(blank=True, help_text='Name of the associated resource (e.g., node3401). Must be unique when provided.', max_length=128, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'CPU Node Instance',
                'verbose_name_plural': 'CPU Node Instances',
                'ordering': ['name', 'associated_resource_address'],
            },
        ),
        migrations.CreateModel(
            name='GpuNodeInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(help_text='GPU node type name (e.g., H200x8, L40Sx4). Multiple instances of the same type are allowed.', max_length=64)),
                ('is_rentable', models.BooleanField(default=False, help_text='Whether this node type can be rented for booking management')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('PLACEHOLDER', 'Placeholder')], default='AVAILABLE', help_text='Current status of the node instance', max_length=32)),
                ('associated_resource_address', models.CharField(blank=True, help_text='Name of the associated resource (e.g., node3401). Must be unique when provided.', max_length=128, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'GPU Node Instance',
                'verbose_name_plural': 'GPU Node Instances',
                'ordering': ['name', 'associated_resource_address'],
            },
        ),
    ]
