# Generated by Django 4.2.23 on 2025-12-18 02:31

from django.db import migrations


def rename_cpu_labels_forward(apps, schema_editor):
    """Rename CPU node type labels from incorrect units to correct units."""
    NodeType = apps.get_model('coldfront_orcd_direct_charge', 'NodeType')

    # Update CPU_384M -> CPU_384G
    NodeType.objects.filter(name='CPU_384M').update(
        name='CPU_384G',
        description='CPU node with 384G memory configuration'
    )

    # Update CPU_1500T -> CPU_1500G
    NodeType.objects.filter(name='CPU_1500T').update(
        name='CPU_1500G',
        description='CPU node with 1500G memory configuration'
    )


def rename_cpu_labels_reverse(apps, schema_editor):
    """Reverse the CPU node type label rename."""
    NodeType = apps.get_model('coldfront_orcd_direct_charge', 'NodeType')

    # Revert CPU_384G -> CPU_384M
    NodeType.objects.filter(name='CPU_384G').update(
        name='CPU_384M',
        description='CPU node with 384M memory configuration'
    )

    # Revert CPU_1500G -> CPU_1500T
    NodeType.objects.filter(name='CPU_1500G').update(
        name='CPU_1500T',
        description='CPU node with 1500T memory configuration'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('coldfront_orcd_direct_charge', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            rename_cpu_labels_forward,
            rename_cpu_labels_reverse,
        ),
    ]
