# Generated by Django 4.2.23 on 2025-12-18 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0006_historicalproject_institution_project_institution'),
        ('coldfront_orcd_direct_charge', '0002_rename_cpu_node_labels'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('start_date', models.DateField(help_text='Reservation starts at 4:00 PM on this date')),
                ('num_blocks', models.PositiveIntegerField(default=1, help_text='Number of 12-hour blocks (1 block = 12 hours, minimum 1, maximum 14)')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Current status of the reservation', max_length=16)),
                ('manager_notes', models.TextField(blank=True, help_text='Notes from the rental manager (visible to requester)')),
                ('node_instance', models.ForeignKey(help_text='The GPU node instance being reserved', on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='coldfront_orcd_direct_charge.gpunodeinstance')),
                ('project', models.ForeignKey(help_text='The project this reservation is associated with', on_delete=django.db.models.deletion.PROTECT, related_name='node_reservations', to='project.project')),
                ('requesting_user', models.ForeignKey(help_text='The user who submitted this reservation request', on_delete=django.db.models.deletion.PROTECT, related_name='node_reservation_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
                'ordering': ['-created'],
                'permissions': (('can_manage_rentals', 'Can manage rental requests'),),
            },
        ),
    ]
