# Generated by Django 4.2.23 on 2025-12-19 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coldfront_orcd_direct_charge', '0003_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='rental_management_metadata',
            field=models.TextField(blank=True, help_text='Internal metadata for rental management (managers only)'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='rental_notes',
            field=models.TextField(blank=True, help_text='Optional notes from the requester about this reservation'),
        ),
    ]
