# Generated by Django 4.2.23 on 2025-12-19 21:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('coldfront_orcd_direct_charge', '0004_reservation_rental_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationMetadataEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('content', models.TextField(help_text='Metadata note content')),
                ('reservation', models.ForeignKey(help_text='The reservation this metadata entry belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='metadata_entries', to='coldfront_orcd_direct_charge.reservation')),
            ],
            options={
                'verbose_name': 'Reservation Metadata Entry',
                'verbose_name_plural': 'Reservation Metadata Entries',
                'ordering': ['created'],
            },
        ),
    ]
