# Generated by Django 4.2.23 on 2025-12-19 21:44

from django.db import migrations


def migrate_metadata_to_entries(apps, schema_editor):
    """Migrate existing rental_management_metadata text to ReservationMetadataEntry."""
    Reservation = apps.get_model('coldfront_orcd_direct_charge', 'Reservation')
    ReservationMetadataEntry = apps.get_model('coldfront_orcd_direct_charge', 'ReservationMetadataEntry')

    for reservation in Reservation.objects.exclude(rental_management_metadata=''):
        if reservation.rental_management_metadata.strip():
            ReservationMetadataEntry.objects.create(
                reservation=reservation,
                content=reservation.rental_management_metadata.strip(),
            )


def reverse_migration(apps, schema_editor):
    """Reverse migration: copy first entry back to rental_management_metadata."""
    Reservation = apps.get_model('coldfront_orcd_direct_charge', 'Reservation')
    ReservationMetadataEntry = apps.get_model('coldfront_orcd_direct_charge', 'ReservationMetadataEntry')

    for reservation in Reservation.objects.all():
        first_entry = ReservationMetadataEntry.objects.filter(
            reservation=reservation
        ).order_by('created').first()
        if first_entry:
            reservation.rental_management_metadata = first_entry.content
            reservation.save(update_fields=['rental_management_metadata'])


class Migration(migrations.Migration):

    dependencies = [
        ('coldfront_orcd_direct_charge', '0005_reservationmetadataentry'),
    ]

    operations = [
        migrations.RunPython(migrate_metadata_to_entries, reverse_migration),
    ]
