# Generated by Django 4.2.23 on 2025-12-20 03:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coldfront_orcd_direct_charge', '0009_create_group_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMaintenanceStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', models.CharField(choices=[('inactive', 'Inactive'), ('basic', 'Basic'), ('advanced', 'Advanced')], default='inactive', help_text='Current account maintenance status', max_length=16)),
                ('user', models.OneToOneField(help_text='The user this maintenance status belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_status', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Maintenance Status',
                'verbose_name_plural': 'User Maintenance Statuses',
            },
        ),
    ]
