# Generated by Django 4.2.23 on 2025-12-20 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_historicalproject_institution_project_institution'),
        ('coldfront_orcd_direct_charge', '0011_create_maintenance_status_for_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermaintenancestatus',
            name='billing_project',
            field=models.ForeignKey(blank=True, help_text='Project to which maintenance fees are charged (required for basic/advanced)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_fee_users', to='project.project'),
        ),
    ]
