# Generated by Django 4.2.23 on 2025-12-20 22:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_historicalproject_institution_project_institution'),
        ('coldfront_orcd_direct_charge', '0012_usermaintenancestatus_billing_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCostAllocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('notes', models.TextField(blank=True, help_text='Notes about the cost allocation for this project')),
                ('project', models.OneToOneField(help_text='The project this cost allocation belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='cost_allocation', to='project.project')),
            ],
            options={
                'verbose_name': 'Project Cost Allocation',
                'verbose_name_plural': 'Project Cost Allocations',
            },
        ),
        migrations.CreateModel(
            name='ProjectCostObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('cost_object', models.CharField(help_text='Cost object identifier (alphanumeric characters and hyphens only)', max_length=64, validators=[django.core.validators.RegexValidator(message='Cost object must contain only letters, numbers, and hyphens', regex='^[A-Za-z0-9-]+$')])),
                ('percentage', models.DecimalField(decimal_places=2, help_text='Percentage of billing allocated to this cost object (0.00 - 100.00)', max_digits=5)),
                ('allocation', models.ForeignKey(help_text='The cost allocation this cost object belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='cost_objects', to='coldfront_orcd_direct_charge.projectcostallocation')),
            ],
            options={
                'verbose_name': 'Project Cost Object',
                'verbose_name_plural': 'Project Cost Objects',
                'ordering': ['-percentage', 'cost_object'],
            },
        ),
    ]
