# Generated by Django 4.2.23 on 2025-12-20 22:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0006_historicalproject_institution_project_institution'),
        ('coldfront_orcd_direct_charge', '0013_project_cost_allocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMemberRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('role', models.CharField(choices=[('financial_admin', 'Financial Admin'), ('technical_admin', 'Technical Admin'), ('member', 'Member')], help_text='The role assigned to the user in this project', max_length=32)),
                ('project', models.ForeignKey(help_text='The project this role assignment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='member_roles', to='project.project')),
                ('user', models.ForeignKey(help_text='The user who has this role', on_delete=django.db.models.deletion.CASCADE, related_name='project_member_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project Member Role',
                'verbose_name_plural': 'Project Member Roles',
                'ordering': ['project', 'role', 'user__username'],
                'unique_together': {('project', 'user')},
            },
        ),
    ]
