# Generated by Django 4.2.23 on 2025-12-20 23:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0006_historicalproject_institution_project_institution'),
        ('coldfront_orcd_direct_charge', '0015_initialize_member_roles'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectmemberrole',
            unique_together={('project', 'user', 'role')},
        ),
    ]
