# Generated by Django 4.2.23 on 2025-12-21 00:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coldfront_orcd_direct_charge', '0016_change_projectmemberrole_unique_constraint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectcostallocation',
            options={'permissions': [('can_manage_billing', 'Can approve/reject cost allocations')], 'verbose_name': 'Project Cost Allocation', 'verbose_name_plural': 'Project Cost Allocations'},
        ),
        migrations.AddField(
            model_name='projectcostallocation',
            name='review_notes',
            field=models.TextField(blank=True, help_text='Notes from the Billing Manager about the review decision'),
        ),
        migrations.AddField(
            model_name='projectcostallocation',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, help_text='When the allocation was reviewed', null=True),
        ),
        migrations.AddField(
            model_name='projectcostallocation',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='The Billing Manager who reviewed this allocation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_cost_allocations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectcostallocation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', help_text='Approval status of this cost allocation', max_length=16),
        ),
    ]
