# Generated by Django 4.2.23 on 2025-12-22 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coldfront_orcd_direct_charge', '0017_add_cost_allocation_approval'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostAllocationSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('approved_at', models.DateTimeField(help_text='When this cost allocation split was approved')),
                ('superseded_at', models.DateTimeField(blank=True, help_text='When this snapshot was replaced by a new approval (null if current)', null=True)),
                ('allocation', models.ForeignKey(help_text='The cost allocation this is a snapshot of', on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='coldfront_orcd_direct_charge.projectcostallocation')),
                ('approved_by', models.ForeignKey(help_text='The Billing Manager who approved this allocation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_cost_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cost Allocation Snapshot',
                'verbose_name_plural': 'Cost Allocation Snapshots',
                'ordering': ['-approved_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoicePeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('year', models.IntegerField(help_text='The year of the invoice period')),
                ('month', models.IntegerField(help_text='The month of the invoice period (1-12)')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('FINALIZED', 'Finalized')], default='DRAFT', help_text='Status of the invoice period', max_length=16)),
                ('finalized_at', models.DateTimeField(blank=True, help_text='When the invoice was finalized', null=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about the invoice period')),
                ('finalized_by', models.ForeignKey(blank=True, help_text='The user who finalized this invoice', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Invoice Period',
                'verbose_name_plural': 'Invoice Periods',
                'ordering': ['-year', '-month'],
                'permissions': [('can_manage_invoices', 'Can manage invoice preparation')],
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='CostObjectSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('cost_object', models.CharField(help_text='Cost object identifier', max_length=64)),
                ('percentage', models.DecimalField(decimal_places=2, help_text='Percentage of billing allocated to this cost object', max_digits=5)),
                ('snapshot', models.ForeignKey(help_text='The snapshot this cost object belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='cost_objects', to='coldfront_orcd_direct_charge.costallocationsnapshot')),
            ],
            options={
                'verbose_name': 'Cost Object Snapshot',
                'verbose_name_plural': 'Cost Object Snapshots',
                'ordering': ['-percentage', 'cost_object'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLineOverride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('override_type', models.CharField(choices=[('HOURS', 'Hours Override'), ('COST_SPLIT', 'Cost Split Override'), ('EXCLUDE', 'Exclude from Invoice')], help_text='Type of override being applied', max_length=16)),
                ('original_value', models.JSONField(help_text='The original calculated values before override')),
                ('override_value', models.JSONField(help_text='The overridden values')),
                ('notes', models.TextField(help_text='Required explanation for why this override was made')),
                ('created_by', models.ForeignKey(help_text='The user who created this override', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_overrides_created', to=settings.AUTH_USER_MODEL)),
                ('invoice_period', models.ForeignKey(help_text='The invoice period this override belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='coldfront_orcd_direct_charge.invoiceperiod')),
                ('reservation', models.ForeignKey(help_text='The reservation being overridden', on_delete=django.db.models.deletion.CASCADE, related_name='invoice_overrides', to='coldfront_orcd_direct_charge.reservation')),
            ],
            options={
                'verbose_name': 'Invoice Line Override',
                'verbose_name_plural': 'Invoice Line Overrides',
                'ordering': ['-created'],
                'unique_together': {('invoice_period', 'reservation')},
            },
        ),
    ]
