# Generated by Django 4.2.23 on 2025-12-25 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coldfront_orcd_direct_charge', '0019_backfill_cost_allocation_snapshots'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action', models.CharField(db_index=True, help_text='Machine-readable action identifier (e.g., reservation.approved)', max_length=100)),
                ('category', models.CharField(choices=[('auth', 'Authentication'), ('reservation', 'Reservation'), ('project', 'Project'), ('member', 'Member Management'), ('cost_allocation', 'Cost Allocation'), ('billing', 'Billing'), ('invoice', 'Invoice'), ('maintenance', 'Maintenance Status'), ('api', 'API Access'), ('view', 'Page View')], db_index=True, help_text='Category of the action for filtering', max_length=30)),
                ('description', models.TextField(help_text='Human-readable description of the action')),
                ('target_type', models.CharField(blank=True, help_text='Class name of the target object (e.g., Reservation, Project)', max_length=100)),
                ('target_id', models.PositiveIntegerField(blank=True, help_text='Primary key of the target object', null=True)),
                ('target_repr', models.CharField(blank=True, help_text='String representation of the target object', max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the request', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser/client user agent string')),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='Additional structured data about the action')),
                ('user', models.ForeignKey(blank=True, help_text='The user who performed this action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='coldfront_o_user_id_0d9eb2_idx'), models.Index(fields=['category', '-timestamp'], name='coldfront_o_categor_274021_idx'), models.Index(fields=['action', '-timestamp'], name='coldfront_o_action_9bddcd_idx')],
            },
        ),
    ]
