# Generated by Django 4.2.23 on 2025-12-30 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coldfront_orcd_direct_charge', '0020_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='processed_by',
            field=models.ForeignKey(blank=True, help_text='The rental manager who approved/declined this reservation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Confirmed'), ('DECLINED', 'Declined'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Current status of the reservation', max_length=16),
        ),
    ]
