# SPDX-FileCopyrightText: (C) ORCD
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# Generated by Django 4.2.23 on 2026-01-26 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0006_historicalproject_institution_project_institution'),
        ('coldfront_orcd_direct_charge', '0025_rename_basic_to_standard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='category',
            field=models.CharField(choices=[('auth', 'Authentication'), ('reservation', 'Reservation'), ('project', 'Project'), ('member', 'Member Management'), ('cost_allocation', 'Cost Allocation'), ('billing', 'Billing'), ('invoice', 'Invoice'), ('maintenance', 'Maintenance Status'), ('rate', 'Rate Management'), ('api', 'API Access'), ('view', 'Page View')], db_index=True, help_text='Category of the action for filtering', max_length=30),
        ),
        migrations.AlterField(
            model_name='rentalrate',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='rentalrate',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='rentalsku',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='rentalsku',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='rentalsku',
            name='sku_type',
            field=models.CharField(choices=[('NODE', 'Node Rental'), ('MAINTENANCE', 'Account Maintenance Fee'), ('QOS', 'Rentable QoS')], help_text='Type of rentable item', max_length=20),
        ),
        migrations.CreateModel(
            name='UserQoSSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this subscription is currently active')),
                ('start_date', models.DateField(help_text='Date when this subscription started')),
                ('end_date', models.DateField(blank=True, help_text='Date when this subscription ended (null if ongoing)', null=True)),
                ('billing_project', models.ForeignKey(blank=True, help_text='Project to which QoS subscription fees are charged', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qos_subscriptions', to='project.project')),
                ('sku', models.ForeignKey(help_text='The QoS SKU for this subscription', limit_choices_to={'sku_type': 'QOS'}, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='coldfront_orcd_direct_charge.rentalsku')),
                ('user', models.ForeignKey(help_text='The user this QoS subscription belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='qos_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User QoS Subscription',
                'verbose_name_plural': 'User QoS Subscriptions',
                'ordering': ['-created'],
            },
        ),
    ]
