# Generated by Django 4.2.23 on 2026-01-31 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coldfront_orcd_direct_charge', '0026_userqossubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceWindow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('start_datetime', models.DateTimeField(help_text='When the maintenance period begins')),
                ('end_datetime', models.DateTimeField(help_text='When the maintenance period ends')),
                ('title', models.CharField(help_text='Short title describing the maintenance', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional detailed description of the maintenance')),
                ('created_by', models.ForeignKey(blank=True, help_text='Rental manager who created this window', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_maintenance_windows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Maintenance Window',
                'verbose_name_plural': 'Maintenance Windows',
                'ordering': ['-start_datetime'],
            },
        ),
    ]
