# Generated by Django 4.2.23 on 2026-04-18 02:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coldfront_orcd_direct_charge', '0030_usermaintenancestatus_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicelineoverride',
            name='override_type',
            field=models.CharField(choices=[('HOURS', 'Hours Override'), ('COST_SPLIT', 'Cost Split Override'), ('EXCLUDE', 'Exclude from Invoice'), ('CHARGE_PROJECT', 'Charge to Different Project')], help_text='Type of override being applied', max_length=16),
        ),
        migrations.AlterField(
            model_name='usermaintenancestatus',
            name='end_date',
            field=models.DateField(default=datetime.date(2100, 1, 1), help_text='Date after which AMF billing stops (rounded up to whole subscription month). Defaults to 2100-01-01 (effectively indefinite).'),
        ),
    ]
